### ISSUE TITLE
Can't configure JKU cache

### ISSUE THREAD

**Issue by symm** [Spomky-Labs/jose-bundle#39]
I'm following the [From a JKU (JSON Wek Key URL)](https://github.com/Spomky-Labs/jose-bundle/blob/master/Resources/doc/config/key_sets.md#from-a-jku-json-wek-key-url) instructions to set up a cache as follows:

```
jose:
  key_sets:
    azure:
      jku:
          url: "https://login.microsoftonline.com/common/discovery/keys"
          is_secured: true
          cache: 'cache.app' # Issue with cache config option
          cache_ttl: 300
```

But am getting the following error:

```
TypeError: Argument 3 passed to Jose\Factory\JWKFactory::createFromJKU() must implement 
interface Psr\Cache\CacheItemPoolInterface or be null, string given
```

It looks like the literal string `cache.app` is being passed through instead of the object from the container.
